---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: mightyfine
  namespace: dev
  annotations:
    flux.weave.works/tag.mightyfined: glob:*
spec:
  replicas: 4
  selector:
    matchLabels:
      app: mightyfine
  template:
    metadata:
      labels:
        app: mightyfine
      annotations:
        prometheus.io/scrape: 'true'
    spec:
      containers:
      - name: mightyfined
        image: quay.io/brice/metrics-demo:master
        ports:
        - containerPort: 3000

